POST http://localhost:3003/api/blogs
Content-Type: application/json
Accept: application/json

{
  "title": "This is the end",
  "author": "Seth Rogen",
  "url": "Tosi hyvän blogin linkki",
  "likes": 99
}